# Generated by Django 5.0.4 on 2024-07-02 06:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='smtg',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='verified',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card',
            field=models.CharField(help_text='Enter your 13-16 digit credit card number.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Credit card number must be 13-16 digits long and contain only numeric characters.', regex='^[0-9]{13,16}$')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flightname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flightnumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
