# Generated by Django 5.0.4 on 2024-07-02 06:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255, null=True)),
                ('card', models.CharField(help_text='Enter your 13-16 digit credit card number.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Credit card number must be 13-16 digits long and contain only numeric characters.', regex='^[0-9]{13,16}$')])),
                ('email', models.EmailField(max_length=255, null=True)),
                ('flightname', models.CharField(max_length=255, null=True)),
                ('logo', models.CharField(max_length=255, null=True)),
                ('flightnumber', models.CharField(max_length=255, null=True)),
                ('departure_time', models.DateField(null=True)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(default=0, max_length=10, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
