# Generated by Django 5.0.4 on 2024-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recipes',
            new_name='bookingID',
        ),
    ]
