# Generated by Django 5.0.4 on 2024-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_recipes_user_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.IntegerField()),
                ('general_amenities', models.TextField()),
                ('dining_amenities', models.TextField()),
                ('wellness_amenities', models.TextField()),
                ('services_amenities', models.TextField()),
                ('room_types', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('nearest_airport_name', models.CharField(max_length=255)),
                ('nearest_airport_code', models.CharField(max_length=10)),
                ('nearest_airport_distance_km', models.FloatField()),
                ('nearest_attractions', models.JSONField()),
                ('dining_options', models.JSONField()),
                ('spa_name', models.CharField(max_length=255)),
                ('spa_treatments', models.TextField()),
                ('spa_facilities', models.TextField()),
                ('wedding_services', models.BooleanField()),
                ('conference_facilities', models.BooleanField()),
                ('pet_friendly', models.BooleanField()),
                ('image_links', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
