# Generated by Django 5.0.4 on 2024-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='conference_facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='dining_options',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image_links',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='nearest_attractions',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_types',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='services_amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='spa_facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='spa_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='spa_treatments',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='website',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='wedding_services',
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_services_conference_facilities',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_services_pet_friendly',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_services_wedding_services',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_info_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_info_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_info_website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dining_options_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dining_options_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dining_options_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nearest_attractions_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nearest_attractions_distance_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nearest_attractions_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_amenities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_image_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_max_occupancy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_amenities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='spa_details_facilities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='spa_details_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='spa_details_treatments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='dining_amenities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='general_amenities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nearest_airport_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nearest_airport_distance_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nearest_airport_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wellness_amenities',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
