# Generated by Django 5.0.4 on 2024-07-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_hotelbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={},
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hbooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hotelbookingID',
            field=models.TextField(null=True),
        ),
    ]
