# Generated by Django 5.0.4 on 2024-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_hotelbooking_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='models',
            new_name='status',
        ),
    ]
